### ISSUE TITLE
UTF with BOM issue

### ISSUE THREAD

**Issue by dfcreative** [browserify/brfs#69]
Hi @substack @mattdesl!

I am having a simple setup:

``` js
const insertCss = require('insert-css');
const fs = require('fs');
insertCss(fs.readFileSync('./index.css', 'utf-8'));
```

I noticed that the first style rule does not get applied. I figured out that `fs.readFileSync('./index.css', 'utf-8').charCodeAt(0)` returns `65279`, which is none of the ASCII range. Brief [googling showed up](http://stackoverflow.com/questions/6784799/what-is-this-char-65279) that that is the reason of saving `index.css` as UTF with BOM. Therefore I am kind of forced doing `fs.readFileSync('./index.css', 'utf-8').trim()` or define UTF format of saving files, which is a kind of no good.

Is there any way to make brfs handle this? Before I used `browserify-css` and it had no such issue.

Thanks.

**Comment by mk-pmb** [comment]
Including the BOM in the result is an exact reproduction of how `fs.readFileSync(…, "utf-8")` behaves. Related issues:
 * https://github.com/nodejs/node-v0.x-archive/issues/1918 " fs.readFileSync(filename, 'utf8') doesn't strip BOM markers"
 * https://github.com/nodejs/node-v0.x-archive/issues/4039 "Add 'utf8-sig' encoding option."
 * [Unicode FAQ](http://unicode.org/faq/utf_bom.html#bom6) "What should I do with U+FEFF in the middle of a file?"

I vote that in order to help debugging, brfs tries its best to exactly copy node.js when it replaces an original node.js API. Most utility libraries won't be detected by brfs, that's sad. I thought about a BOM-stripping API for brfs-aware code but to me that seems too bloaty compared to `.replace(/^\uFEFF/, '')`. How about this?

```js
const insertCss = require('insert-css');
const fs = require('fs');
const noBOM = function (s) { return String(s).replace(/^\uFEFF/, ''); };
insertCss(noBOM(fs.readFileSync('./index.css', 'utf-8')));
```

In this special case, I'd even expect that insert-css takes care of that. With its special knowledge that the data is meant as CSS, it can reliably decide that it's valid to auto-strip the BOM at its start.

**Comment by mk-pmb** [comment]
The `insert-css` was updated to strip the BOM.

**Comment by goto-bus-stop** [comment]
looks like intended behaviour then. thanks!
