### ISSUE TITLE
brfs breaks source maps

### ISSUE THREAD

**Issue by mikolalysenko** [browserify/brfs#7]
I love brfs, but this issue is right now my number one annoyance.  To replicate this, take any multifile bundle and add an fs.readSync with brfs.  Open up the result in chrome, and you get a single giant blob.

Any ideas on what could be done to fix this situation?

**Comment by revolunet** [comment]
any news on this ? can brfs support source maps ?

**Comment by mattdesl** [comment]
I am not sure this issue will ever be solved with the current iteration of `static-module` – it will take a refactor (which might be worthwhile since that module has gotten pretty hairy) or building on top another source transformer altogether.

I experimented with the latter here:
https://github.com/Jam3/brfs-babel

It supports some (but not all) of brfs use cases, and since it builds on babel some aspects (like removing nodes) are very trivial without worrying about source maps. However, babel does not support async transformations, so it will probably never replace `static-module`.

**Comment by goto-bus-stop** [comment]
https://github.com/browserify/brfs/commit/f8c924a49156139c36d2a510181929028fc75b76

:package: 1.5.0

**Comment by boris-ulyanov** [comment]
Update 1.4.4 to 1.5.0 breaks sourcemap for my case:
- node 8.9.4
- budo 11.2.0 /  browserify 16.1.0

**Comment by blackgate** [comment]
This should be reopened. Still breaks the sourcemaps here too.

**Comment by goto-bus-stop** [comment]
In what way? Can you share an example?

**Comment by blackgate** [comment]
Sure:
```js
const fs = require("fs");
const browserify = require("browserify");
browserify("./script.js", { debug: true })
  .transform("babelify", {presets: ["env"], sourceMaps: true})
  .transform("brfs")
  .bundle()
  .pipe(fs.createWriteStream("bundle.js"));
```
With the `.transform("brfs")` line, the sourcemap contains the transpiled source instead of the original.

**Comment by goto-bus-stop** [comment]
Thanks, moving to https://github.com/browserify/brfs/issues/86!
